### ISSUE TITLE
NotImplementedType thrown when using encfs

### ISSUE THREAD

**Issue by zpon** [sondree/b2_fuse#63] opened 2018-03-31 08:40 UTC
When encfs is enabled I get the following stacktrace when moving data to the encrypted folder.

```
$ ./b2fuse.py --temp_folder dst/tmp/ dst/mnt/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 604, in write
    offset, fh)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/private/tools/b2_fuse/b2fuse_main.py", line 436, in write
    self.open_files[path].write(offset, data)
  File "/home/private/tools/b2_fuse/filetypes/B2SequentialFileMemory.py", line 75, in write
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 604, in write
    offset, fh)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/private/tools/b2_fuse/b2fuse_main.py", line 436, in write
    self.open_files[path].write(offset, data)
  File "/home/private/tools/b2_fuse/filetypes/B2SequentialFileMemory.py", line 75, in write
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
```
`encfs` command:
```
$ encfs $PWD/dst/mnt/ $PWD/dst/crypt/
[...]
$ cp sample.txt dst/crypt/
cp: error writing 'dst/crypt/sample.txt': Input/output error
```

**Comment by zpon** [comment] 2018-03-31 15:45
It looks like the problem is (at least partially) caused by a new version of b2 python library. This change removes `bytes_io` from `DownloadDestBytes`: https://github.com/Backblaze/B2_Command_Line_Tool/commit/003aeb5511b9789a491403c56fee8c53a79d1322#diff-973bb4c8f3ad097d9a58d1a8e4c21b97

I have attached a small diff which allowed me to get `encfs` running: [diff.txt](https://github.com/sondree/b2_fuse/files/1865637/diff.txt)

**Comment by KonstantinSchubert** [comment] 2018-04-02 15:35
This seems unrelated to encfs, I am getting the same error just with  
```
python b2fuse.py <mountpoint>
```
@zpon There is a small bug in your diff, I think it should read `get_bytes_written` instead of just `bytes_written` in the second case as well.

@zpon Maybe this has better chances to get applied if you open a pull request? I might also do it, but I want to leave you the first move since you were the one to discover the fix.

@sondree How about adding a setup.py, publishing to pipy  and thereby defining the dependencies? This would help to avoid bugs such as this one. Let me know if I can help with that. (Related to: https://github.com/sondree/b2_fuse/issues/26)

**Comment by falense** [comment] 2018-04-02 18:13
I have added the basic fix. There is still another issue that I believe is related to your use of the _--temp_folder_ argument in conjunction with encfs. I tried to go through the basics steps with a new empty bucket without this argument and it worked fine. I will see if there is an easy way to make _--temp_folder_ work. 

@KonstantinSchubert  Please add a setup.py if you know how to. I think this would be a good addition to B2Fuse. Can you make a pull request?

**Comment by falense** [comment] 2018-04-02 18:43
I believe that  84bf48c  should resolve the issue you were seeing. Note that the use of the _--temp-folder_ does nothing if not used in conjunction with _--use_disk_. The issue you were seeing were caused by random access to a file which was stored sequentially in memory. The fix is crude but functional, as I have to extend the in memory file to whatever offset the application is trying to read. This is as good as it gets, but could cause troubles if an application tries to access for example a byte at address 1 trillion which would try to allocate 116GB of memory. In normal use it will likely be okay though.

**Comment by falense** [comment] 2018-04-02 19:46
@KonstantinSchubert As mentioned previously, you are more than welcome to contribute a setup.py to the project and please let me know what we need to do get this listed on PIP. I will close this issue as the commits fixes the problem, but feel free to open another to address listing B2Fuse on PIP (or use the old enhancement issue #26)

**Closed as completed by falense** 2018-04-02 19:46 UTC
Labels: bug

**Comment by zpon** [comment] 2018-04-07 15:45
Could you elaborate on the `--use_disk` and `--temp-folder` options? They are only briefly described in the README.md.

**Comment by falense** [comment] 2018-04-08 09:17
_use_disk_ is what actually trigger a change in behavior of B2Fuse. The intention of the disk backed storage was to allow for files that are larger than what can fit in ram. The default mode of operation stores all the files in ram while they are being accessed. The _temp_folder_ argument just allows you to override the default disk storage location.
