### ISSUE TITLE
SHA1 files appear on directory listing

### ISSUE THREAD

**Issue by nilayp** [sondree/b2_fuse#2] opened 2015-12-22 08:39 UTC
Sondre- moving our conversation to github.:)

When I mount a bucket and ls the directory - I'm seeing the a file with the extension .sha1 for each file in my directory. When I try to cat the file, I get the following error: cat: img.jpg.sha1: Bad address.

-- Nilay

**Comment by falense** [comment] 2015-12-22 09:08
This must have been a regression issue, during one of my code cleanups. Try fetching latest now.

**Comment by falense** [comment] 2015-12-22 09:10
Fix exists in commit bfa2f837a2cbc32fce6a2a6a076aac579ab50474

**Comment by nilayp** [comment] 2015-12-22 19:32
I pulled the new version, and tried it... the .sha1 files are still appearing.

-- Nilay

**Comment by falense** [comment] 2015-12-22 21:43
This is intended behaviour (and is described in the readme). Basically it
exposes the sha1 hashes computed server side for easier comparison with
local variants. With these, you could get the hash of the file without
downloading it first. How to disable this function is also described in the
readme.

With the fix, you should now be able to view/cat the ".sha1" files.

I should probably make this optional using a command line parameter.

**Comment by nilayp** [comment] 2015-12-23 20:05
It works. I can now cat the .sha1 files... and hide them with the config flag. Thanks.

**Comment by falense** [comment] 2015-12-23 22:07
I'm going to close this issue now, as the bug in question is actually fixed. If you have further issues or questions, feel free to open another issue ;)

**Closed as completed by falense** 2015-12-23 22:07 UTC
Labels: bug
