### ISSUE TITLE
1000 files per bucket limit

### ISSUE THREAD

**Issue by bjesus** [sondree/b2_fuse#1] opened 2015-12-14 08:43 UTC
Thanks for b2_fuse !

I'd like to backup my music collection to B2, but this limitation makes it impossible as I have around 50,000 files in it. Why is the limitation? As I understood [here](https://help.backblaze.com/entries/96512157-B2-Beta-What-is-Working-Partially-Working-Not-Working-NOV-18), the API allows me to upload unlimited amount of files per bucket.

Anything I can do to solve it?

Thanks again!

**Comment by falense** [comment] 2015-12-14 16:49
Each call to B2 listing files, will return at most 1000 files. So for your
example, loading the entire file list for the bucket would take 50 calls.
Each call to B2 takes 1-2 seconds, so the initial start-up would take
50-100 seconds (to load all your files). After that, the file list is
cached until you update the bucket ( upload or delete a file) at which
point it has to be refreshed. A refresh would take another 50-100s.

I'm interested in hearing what would be acceptable behaviour for these
cases. Updating the library so that it fetches all the files is a quick fix
(just a couple of lines of code), but if you actually attempted to use it
as you describe you would need to wait 2minutes between each file upload
(each time you upload a file your file explorer will refresh the directory
content to check that the file was written successfully).

I could cache the file list and correct for whatever you did to change the
bucket locally, this would reduce the need for refreshing the file list.
The downside of this approach is that if you added files using another
machine, at more or less the same time, these would not become visible
until the file list is refreshed. As it stands I have tried to implement
the driver in the most transparent way possible (as to expose what exists
in B2), but I am open for input on these issues.

Please, do ask if this was unclear. I too am interested in a way to
circumvent these latency issues.

Best regards
1. des. 2015 09.43 skrev "bjesus" notifications@github.com:

**Comment by bjesus** [comment] 2015-12-17 11:32
Thanks for the reply! I understand the issue now.

It seems that the b2_list_file_names call needs an option to work in a non-recursive way, otherwise I really can't think of a solution. I guess that's what directories are for - I don't have my 50,000 files all in one directory - it's divided into in a music/<artist>/<album>/<file> hierarchy. If there could be a way to list only what I have in the "music" directory, then that would have taken only two requests. Checking that a file was uploaded would take only one as I obviously not have more than a 1,000 files in an album.

Anyway, as for when uploading, wouldn't it make more sense to use b2_get_file_info rather than to list all the files again? and actually, why do even that, if b2_upload_file already tells you the fileName and contentLength of it? Can't we trust that to confirm that the file was uploaded successfully?

Thanks again!

**Comment by falense** [comment] 2015-12-17 12:26
You're welcome ☺

Yes, the reply from the upload api call could be used to locally maintain a
consistant copy of the directory structure.

It is actually your file explorer, refreshing the directory content
listing, that causes the call to list all files in the B2 bucket. It would
be possible to delay this, by updating the cache locally, as mentioned
above. The main issue remains though; you cannot list files just in one
directory. I have suggested such an api call as an enhancement to B2.

Would the addition of a locally updated cache make the application usable
in your case? This would let you upload files faster (and download) but the
initial startup would still take 1-2minutes.
17. des. 2015 12.32 skrev "bjesus" notifications@github.com:

**Comment by bjesus** [comment] 2015-12-17 14:32
Possibly it will make it more usable, yes.

I'm not planning on using a file explorer, mostly CLI and hopefully I'll manage to get it to play nicely with [SubSonic](http://subsonic.org). I have no idea how it works regarding updates to DB etc', so I'll just have to check and see.

**Comment by falense** [comment] 2015-12-17 18:52
@bjesus  Latest on master branch contain the changes mentioned. Give it a go :-)

**Comment by bjesus** [comment] 2015-12-22 09:59
I can't get it to work. Seems like rsync creates the directories structure but get stuck trying to upload the first file.

```
...
2015-12-22 11:20:35,271:DEBUG:Memory used 0.0
2015-12-22 11:20:35,271:INFO:_list_dir 
2015-12-22 11:20:35,271:DEBUG:Get attr /.sync/Archive
2015-12-22 11:20:35,271:DEBUG:Memory used 0.0
2015-12-22 11:20:35,271:INFO:_list_dir 
2015-12-22 11:20:35,271:DEBUG:Mkdir /.sync/Archive (mode:448)
2015-12-22 11:20:35,271:INFO:_list_dir 
2015-12-22 11:20:35,275:DEBUG:Get attr /.sync/Archive
2015-12-22 11:20:35,275:DEBUG:Memory used 0.0
2015-12-22 11:20:35,276:DEBUG:Utimens /.sync/Archive
2015-12-22 11:20:35,276:DEBUG:Get attr /.sync/Archive
2015-12-22 11:20:35,276:DEBUG:Memory used 0.0
2015-12-22 11:20:35,276:DEBUG:Get attr /musiclibrary.blb
2015-12-22 11:20:35,276:DEBUG:Memory used 0.0
2015-12-22 11:20:35,276:INFO:_list_dir 
2015-12-22 11:20:35,276:INFO:_list_dir 
2015-12-22 11:20:35,276:INFO:get_file_info musiclibrary.blb
2015-12-22 11:20:35,276:INFO:_list_dir 
2015-12-22 11:20:35,277:DEBUG:Chmod /.sync/Archive (mode:16877)
2015-12-22 11:20:35,277:DEBUG:Get attr /.sync/Archive
2015-12-22 11:20:35,277:DEBUG:Memory used 0.0
2015-12-22 11:20:35,277:DEBUG:Open /musiclibrary.blb (flags:32768)
2015-12-22 11:20:35,277:INFO:_list_dir 
2015-12-22 11:20:35,277:INFO:get_file musiclibrary.blb
```

At this point rsync seems to hang on uploading musiclibrary.blb, and trying to `Ctrl`+`C` it yielded this after a minute: `[sender] io timeout after 60 seconds -- exiting`.

Even after killing rsync I can't access the mounted folder, `ls`ing it gives a timeout etc'.

**Comment by falense** [comment] 2015-12-22 13:27
All access to the FUSE filesystem is serialized. So if one request has yet to complete, all other request (including listing a directory) will wait (i.e timeout). 

How large is the "musiclibrary.blb" file?

**Comment by bjesus** [comment] 2015-12-23 10:11
It's 112MB :neutral_face:

**Comment by falense** [comment] 2015-12-23 10:31
Typically, on my system, I can get a write speed to the FUSE mounted bucket
at about 1.7MB/s. So this file should have taken me about 66 seconds to
upload. How long did you wait?

The read and write speed is typically limited by the internet down and up
speed, as provided by your isp. The exception is small files, where latency
limits the throughput (each file upload has a constant request time of
1-2 seconds).

**Comment by falense** [comment] 2016-01-03 21:54
Closing this issue as the owner is unresponsive and I am unable to reproduce.

**Closed as completed by falense** 2016-01-03 21:54 UTC
Labels: enhancement, help wanted, question
