### ISSUE TITLE
Issues with Bacula and B2Fuse from lack of permission support

### ISSUE THREAD

**Issue by magedshaker** [sondree/b2_fuse#48] opened 2017-03-11 16:02 UTC
When i running bacula to save backup volume files at mount point of b2fuse filesystem is displayed volume 0 byte and jobs still running for long time with not able to open files are created with no such file or directory , also not able to chown any sub folder at mybucket with error read-only file system although my mount point as your see below 
B2Fuse on /mnt/bb type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)

**Comment by falense** [comment] 2017-03-11 16:04
There is no permissions in B2Fuse. As for why Bacula does not manage to save files I have no idea. Have you tried to create a file manually?

**Comment by magedshaker** [comment] 2017-03-11 17:37
I think some restriction for name as you see below 
 Warning: mount.c:248 Open device "FileStorage" (/mnt/bb/bacula) Volume "Incr.folder05-0142" failed: ERR=dev.c:661 Could not open: /mnt/bb/bacula/Incr.folder05-0142, ERR=No such file or directory

Also what's you mean about 

> There is no permissions in B2Fuse

**Comment by magedshaker** [comment] 2017-03-11 20:56
Also which Linux Distribution support b2fuse other ubuntu

**Comment by falense** [comment] 2017-03-12 10:56
B2 and hence B2Fuse does not have a concept of permissions. There is no permissions in B2 and there is no permissions in B2Fuse. All files are by default RWX to everyone. 

There is no naming restrictions. I tried with the filename you indicated "Incr.folder05-0142" and I can create a file with that name without any issues. I think the problem is rather that Bacula uses some filesystem feature that behaves unexpectedly (because of the difference between B2 and a regular filesystem). 

In theory B2Fuse should support all linux distributions that have the required packages: python, python-yaml, pip, setuptools, B2CLI (python library).

**Comment by magedshaker** [comment] 2017-03-18 16:56
Bacula once create a volume file and chown to bacula , so that't the issue , so no chance to add support of permission to b2fuse

**Comment by ayunt** [comment] 2017-07-13 19:13
Hi, my application runs not under the root and as a result can't use the mount point folder. 

B2Fuse on /b2bucket type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)

The specified location (/b2bucket) does not exist

su -s /bin/bash test_user
bhsvc@va:/$ ls -las /b2bucket
ls: cannot access '/b2bucket': Permission denied
$ ls -las /
 ? d?????????   ? ?    ?        ?            ? b2bucket

Do you have any solution on this?

**Comment by dv-anomaly** [comment] 2017-07-23 08:24
@ayunt  This probably warrants filing a new bug. But the problem is that `allow_other` needs to be used for it to work in that situation.

**Comment by IamDH4** [comment] 2017-07-23 08:30
@ayunt  Changing the last line of `b2fuse.py` should get this working for you. Adding a command line switch would be trivial.

from:
```
FUSE(filesystem, args.mountpoint, nothreads=True, foreground=True)
```
to:
```
FUSE(filesystem, args.mountpoint, nothreads=True, foreground=True,**{'allow_other': True})
```

**Comment by dv-anomaly** [comment] 2017-07-23 09:00
@ayunt see the referenced pull request / fork above, using the flag `--allow_other` will fix that problem.

**Comment by falense** [comment] 2017-07-23 09:43
@IamDH4 fix has been merged (thanks :+1: ), please try it out if you can @ayunt. Closing this thread as is is off topic, please open another issue if the problem persists

**Closed as completed by falense** 2017-07-23 09:43 UTC
Labels: enhancement
