### ISSUE TITLE
only one file being displayed in b2fuse after a 'b2 sync'

### ISSUE THREAD

**Issue by bigtonylewis** [sondree/b2_fuse#60] opened 2017-08-28 03:13 UTC
If I use 'b2 sync <srcdir> b2://<bucketname>/<destdir>' and then mount with b2fuse, only the first file is shown.
I am using commit 1292abd7a74014cf097fe072654581c29455105a from Sun Jul 23 11:41:52 2017 +0200.
Steps to reproduce:
1. create a bucket (here, its name is 4d9ad9cc-eb06-4a32-a734-db949c0c7b86 and the bucket id is 72c9ef62c80425665ae50812)
2. create some random files:
```
mkdir ~/corpus
cd ~/corpus
for n in `seq 0 9`; do
    dd if=/dev/urandom of=`uuidgen` bs=1024k count=1
done
ls -la ~/corpus
```
This shows:
```
total 10248
drwxr-xr-x  2 root root    4096 Aug 28 03:08 .
drwx------ 18 root root    4096 Aug 28 03:08 ..
-rw-r--r--  1 root root 1048576 Aug 28 03:08 169af7c2-814a-441b-bf29-ef4d1ed3c610
-rw-r--r--  1 root root 1048576 Aug 28 03:08 1ab37ba5-dd2f-463c-a8dc-72c8a0811edd
-rw-r--r--  1 root root 1048576 Aug 28 03:08 3bd5f865-4258-4379-9ef6-6cbdbc920e42
-rw-r--r--  1 root root 1048576 Aug 28 03:08 5bfe5791-0840-4bf8-8c38-daf7fc5fa1fa
-rw-r--r--  1 root root 1048576 Aug 28 03:08 72a19896-783c-461d-a45d-eb547ebd89f8
-rw-r--r--  1 root root 1048576 Aug 28 03:08 7a585d16-eccf-4a71-a045-8240ab0b58f7
-rw-r--r--  1 root root 1048576 Aug 28 03:08 7fb9008f-6e04-40e6-a7b6-f3287c0389a4
-rw-r--r--  1 root root 1048576 Aug 28 03:08 9050721d-f13e-44a9-ab1a-bd99e67d4232
-rw-r--r--  1 root root 1048576 Aug 28 03:08 abcf9ad5-74f3-4159-853d-d28debec7c80
-rw-r--r--  1 root root 1048576 Aug 28 03:08 c5588693-a9fc-43c0-be3e-28734ce82f58
```
3. sync the files
```
b2 sync ~/corpus b2://4d9ad9cc-eb06-4a32-a734-db949c0c7b86/corpus
```
`4. create the config file
```
cat > config.yaml <<EOF
accountId: <accountId>
applicationKey: <applicationKey>
bucketId: 72c9ef62c80425665ae50812
EOF
```
5. mount the bucket
```
mkdir ~/b2
b2fuse.py --config ~/config.yaml ~/b2
```
6 list the contents
```
cd ~/b2
cd corpus
ls -la
```

Results: I see:
```
total 0
drwxrwxrwx 2 root root       0 Aug 28 03:11 .
drwxrwxrwx 2 root root       0 Aug 28 03:11 ..
-rwxrwxrwx 1 root root 1048576 Aug 28 03:08 169af7c2-814a-441b-bf29-ef4d1ed3c610
```

That is, only one of the files, not all 10.

If I browse to the bucket through the B2 web interface, all files are there, so there seems to be some problem with b2fuse's ability to show all the files.

**Comment by jtrott** [comment] 2017-09-19 06:53
I'm seeing the same problem, only one file is visible in the mounted b2 bucket. 3 files are visible on the website and through other third party b2 integrated clients.

**Comment by falense** [comment] 2018-04-02 19:43
With a bucket mounted at "mountpoint", I just did: 

```
cd ~/mountpoint
for n in `seq 0 9`; do
    dd if=/dev/urandom of=`uuidgen` bs=1024k count=1
done
ls -lah
```

This lists all the files correctly. Then I unmount the bucket and remount it, it still lists the files correctly. 

I do not use B2 Sync command line application myself, so I cannot comment on any interactions between B2Fuse and B2.

**Comment by falense** [comment] 2018-04-02 19:54
Actually, come to think of it I am sure this is related to issue #53. The files are created fine and shows up as usual unless they are in a subfolder, in which case only the first file shows up. This is now a duplicate of issue #53, please keep all relevant discussion to #53.

**Closed as completed by falense** 2018-04-02 19:54 UTC
Labels: bug, invalid, question
