### ISSUE TITLE
Segmentation Fault - Out of memory

### ISSUE THREAD

**Issue by jasonehines** [sondree/b2_fuse#5] opened 2016-03-03 01:56 UTC
I just tried this for the first time and tried to do an ls on the mount point. I had python running in one terminal and my ls in the other. I could see the program getting the files from b2 in the python terminal. After a few minutes I got a segmentation fault.

Here's the bucket details:
`Current Files: 435,185
Current GB: 635.111 GB`

This is the only thing I see in the syslog that might be helpful (let me know if you want something else):
`Mar  2 20:42:16 files kernel: [20445.742796] show_signal_msg: 30 callbacks suppressed
Mar  2 20:42:16 files kernel: [20445.742801] python[13715]: segfault at 24 ip 0000000000558077 sp 00007fffd3521310 error 6 in python2.7[400000+2bc000]
Mar  2 20:42:16 files kernel: [20445.763319] Core dump to |/usr/share/apport/apport 13715 11 0 13715 pipe failed
`

**Comment by falense** [comment] 2016-03-03 16:37
There are a couple of issues here:
1. With 435 185 files I estimate it would take ~11minutes to load the bucket. This is due to the file listing call in the B2 API taking aprox 1.5 seconds and returning only 1000 files per call.
2. Files are cached in memory. How large is the largest file you store? Is it larger than available memory? 

Could you try to run it again and this time watch the memory consumption through "htop" or similar?

**Comment by lukehebb** [comment] 2016-03-04 07:51
Are files only cached in memory while being written or opened? I'm assuming that once the file is stored on B2 it is removed from memory? (sorry for jumping on someone else's issue, wasn't sure of how to contact you :-) )

**Comment by falense** [comment] 2016-03-04 08:04
I have implemented a buffering mechanism, during read or write the file has to be kept in memory. This is to allow for randomized read and upload of potentially modified file. Once the file is closed the file does not have to be kept in memory (and is only stored on B2).

There is a small buffer, 128MB by default, kept for files. This is set using the "memory_limit" argument in the source code. What this means is that at most 128MB will be used to store files in memory, in the long run. One of the problems I suspect @jasonehines  may have run into, is that if you have a single large file this will still have to be stored in memory (for read and write) even if it is larger than the "memory_limit". The application will attempt to keep the memory usage below 128MB by deleting data from closed files, starting with the largest file in memory. The memory used for the large file cannot be freed before the file is closed.

In addition there is multiple levels of caching in order to make file operations more effective. This is typically an entry with meta information about the files and does not contain the content itself. With very very many files (100 000s) this may also become an issue.

For the future, the best way to contact me is to open an issue and ask a question ;)

**Comment by jasonehines** [comment] 2016-03-07 18:30
I just ran it watching it in htop. It consumed 273 MB before I killed it (I only had 65 MB free). Most of the files in the bucket are about 8 MB.

let me know what else I can do to help.

**Comment by falense** [comment] 2016-03-07 19:48
It does not sound like you ever get past loading the directory structure. Tests I have done locally with a much smaller bucket (20k files) indicate that approximately 1.4-1.8MB ram is required per 1k files. This is the meta data associated with the files, including file names, size, hash etc. There is currently no way to get around this issue, as the B2 API does not support filtering based on directories. 

Here is an example of the data stored per file:

> {u'action': u'upload', u'uploadTimestamp': 1456348427000, u'fileName': u'assembler.html', u'size': 15280, u'fileId': u'4_zca102999930b818150541322_f112d6f1538400c39_d20160224_m211347_c001_v0001017_t0010'}

Right now I cannot see any simple way of reducing the size of each entry. Bottom line loading your bucket with 435 185 files would take aprox. 783 MB of memory. 

I have previously suggested adding a way of filtering based on directories to the B2 API to the Backblaze team. If you feel this is would add value to the service provided by Backblaze I encourage you too to open an enhancement ticket to the Backblaze team. See https://help.backblaze.com/entries/97056537-B2-Beta-How-to-File-a-B2-Bug-or-Enhancement for additional details on requesting features.

**Comment by falense** [comment] 2016-03-07 19:51
Just a quick update, the point of filtering based on directories is to allow for a much more natural way of viewing a bucket. Basically B2Fuse could at each level of the directory tree only requests the folders and files in that current folder instead of first having to request a listing of all the files in your bucket.

**Comment by jasonehines** [comment] 2016-03-07 21:15
I agree. It is difficult to manage the buckets. That's exactly why I wanted to use your code :)

I was previously testing this on a Digital Ocean box with 1GB of ram. I set it up on my machine and tried to debug it in pycharm (never used it before). But with my machine having more resources I was able to let it run for awhile. The resources were fairly low (100-300MB) when it was getting the list of files that were mkv files (about 8MB each). But when it got to the jpg files it spiked to about 1GB of memory.

Isn't the b2 api just returning json (i.e. text) when you get the file list? I don't understand why that would require so much memory. Or is it a fuse issue?

**Comment by falense** [comment] 2016-03-07 21:58
That is odd, there should be no difference in the amount of meta data whether the file is a large or small file or depending on the size of the file stored.  Do you have very many jpg files? 

Yes, B2 API returns json (i.e text). The example I posted above is more or less the same as returned by the B2 API.  As text, the length of the example above is 204 characters long, apparently storing this as a dictionary uses approx 1.4 KB memory in Python. For each file you have the FUSE driver 1.4KB of ram is used on the machine mounting the bucket. 

With such a large amount of files that you have the 1.4 KB per file adds up to 609 259 KBytes or ~600 MB of ram. This is an optimistic estimate as I saw ram usage of up to 1.8 KB per file in my tests. To solve this we need a way to query B2 for a list of files in a given directory, without requesting (and having to store) a list of all the files in your bucket. 

The issues you are experiencing is caused by limitations of the B2 API making the FUSE driver (and any application requiring to list the files in the bucket) very inefficient.

**Comment by jasonehines** [comment] 2016-03-07 23:17
Does the entire bucket list have to be in memory? If so, is that because of the b2 api or FUSE?

Would writing to a database (sql or no sql) before implementing the FUSE part help?

**Comment by jasonehines** [comment] 2016-03-08 00:27
So I did one more test. Closed everything I could and ran the script and let it run for 30 min or so. When I came back I had this in the terminal
`2016-03-07 19:08:51,927:DEBUG:Access / (mode:4)
2016-03-07 19:08:51,929:DEBUG:Get attr /autorun.inf
2016-03-07 19:08:51,929:DEBUG:Memory used 0.0
2016-03-07 19:08:52,142:DEBUG:Readdir /
2016-03-07 19:08:57,026:DEBUG:Get attr /.Trash
2016-03-07 19:08:57,026:DEBUG:Memory used 0.0
2016-03-07 19:08:57,238:DEBUG:Get attr /.Trash-1000
2016-03-07 19:08:57,238:DEBUG:Memory used 0.0
2016-03-07 19:08:57,449:DEBUG:Get attr /user
2016-03-07 19:08:57,449:DEBUG:Memory used 0.0
2016-03-07 19:08:57,450:DEBUG:Readdir /
2016-03-07 19:09:02,286:DEBUG:Get attr /user
2016-03-07 19:09:02,286:DEBUG:Memory used 0.0
2016-03-07 19:09:02,287:DEBUG:Readdir /
2016-03-07 19:09:07,070:DEBUG:Get attr /user
2016-03-07 19:09:07,071:DEBUG:Memory used 0.0
2016-03-07 19:09:07,071:DEBUG:Readdir /
2016-03-07 19:09:11,800:DEBUG:Get attr /user
2016-03-07 19:09:11,801:DEBUG:Memory used 0.0
2016-03-07 19:09:11,801:DEBUG:Readdir /
2016-03-07 19:09:16,510:DEBUG:Get attr /user
2016-03-07 19:09:16,511:DEBUG:Memory used 0.0
2016-03-07 19:09:16,511:DEBUG:Readdir /
2016-03-07 19:09:21,392:DEBUG:Get attr /user
2016-03-07 19:09:21,393:DEBUG:Memory used 0.0
2016-03-07 19:09:21,393:DEBUG:Readdir /
2016-03-07 19:09:26,159:DEBUG:Get attr /user
2016-03-07 19:09:26,159:DEBUG:Memory used 0.0
2016-03-07 19:09:26,160:DEBUG:Readdir /
2016-03-07 19:09:30,891:DEBUG:Get attr /user
2016-03-07 19:09:30,892:DEBUG:Memory used 0.0
2016-03-07 19:09:30,892:DEBUG:Readdir /
2016-03-07 19:09:35,679:DEBUG:Get attr /user
2016-03-07 19:09:35,679:DEBUG:Memory used 0.0
2016-03-07 19:09:35,679:DEBUG:Readdir /
2016-03-07 19:09:40,596:DEBUG:Get attr /user
2016-03-07 19:09:40,596:DEBUG:Memory used 0.0
2016-03-07 19:09:40,597:DEBUG:Readdir /
2016-03-07 19:09:45,395:DEBUG:Get attr /user
2016-03-07 19:09:45,396:DEBUG:Memory used 0.0
2016-03-07 19:09:45,396:DEBUG:Readdir /
2016-03-07 19:09:50,202:DEBUG:Get attr /user
2016-03-07 19:09:50,202:DEBUG:Memory used 0.0
2016-03-07 19:09:50,202:DEBUG:Readdir /
`
The memory usage was 747MB while this was in the terminal.

![b2fuse](https://cloud.githubusercontent.com/assets/870809/13588022/79b3682c-e49a-11e5-89de-a3d3a6145d07.png)

So I went to the mountpoint and did a ls and it started querying b2 again; like when the script first ran.

I think there needs to be some kind of cache even if the actual files aren't cached. Let me know what you think and if I can help.

**Comment by falense** [comment] 2016-03-08 06:42
There is a cache, but the cache timeout is set to 60 sec by default. Likely
the cache timed out before you came back. Se b2bucket_cached for more
details.

**Comment by falense** [comment] 2016-03-08 18:34
Actually, the timeout is set to 120 second at the moment. You can change the timeout for the cache by editing the _b2bucket_cached.py_:

>  cache_timeout=120

This sets the cache timeout in seconds.

**Comment by jasonehines** [comment] 2016-03-14 15:07
I'm trying to remove a bunch of old files from that large bucket. I ended up increasing the timeout to a day but it still gets the list of files from b2 when I try to delete a folder. Python is also using about 4.5 GB of memory. However I haven't gotten the segmentation fault yet.

**Comment by falense** [comment] 2016-03-14 16:19
When you delete files the cache becomes inconsistive/bad. To partially
solve this issue the b2fuse driver attempts to update the local cache with
the deletions you requested.

I am unsure right now why yours is refreshing the directory listing. The
memory usage could at least in part be caused by the caching, as multiple
copies of the directory tree is kept in different caches.

**Comment by J-Wick4** [comment] 2016-04-16 09:08
I just setup and installed a Cento 7.1 DO droplet just like Jason and also ran into an error. I want to use B2 to toss encrypted sever backups, which are chunked at 1GB. However, I'm also getting memory faults. I tried again with a file smaller than available memory and it also failed with output...

2016-04-16 04:05:04,754:DEBUG:Write /backup_1604160233.tar17 (len:3244 offset:772829184)
2016-04-16 04:05:04,755:DEBUG:Flush /backup_1604160233.tar17 1
2016-04-16 04:05:04,755:INFO:_put_file backup_1604160233.tar17 (len:772832428)
2016-04-16 04:05:04,756:INFO:get_file_versions backup_1604160233.tar17
2016-04-16 04:05:05,125:INFO:_delete_file backup_1604160233.tar17 (0)
2016-04-16 04:05:05,125:INFO:_delete_file File deleted (backup_1604160233.tar17) 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/usr/lib/python2.7/site-packages/fuse.py", line 621, in flush
    return self.operations('flush', self._decode_optional_path(path), fh)
  File "/usr/lib/python2.7/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(_args)
  File "b2fuse.py", line 456, in flush
    self.bucket.put_file(path, self.open_files[path])
  File "/root/b2_fuse/b2bucket_cached.py", line 149, in put_file
    file_info = super(B2BucketCached, self)._put_file(_args)
  File "/root/b2_fuse/b2bucket.py", line 148, in _put_file
    with OpenUrl(upload_url.encode('ascii'), data, encoded_headers) as response_file:
  File "/root/b2_fuse/b2_python_pusher.py", line 61, in __enter__
    self.file = urllib2.urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain

AND
[root@backup pleskbackup]# cp backup_1604160233.tar17 /home/b2/
cp: failed to close ‘/home/b2/backup_1604160233.tar17’: Bad address

## Update:

Tried with a 200MB file and it worked.

2016-04-16 04:17:49,743:DEBUG:Write /200MB.zip (len:4096 offset:209702912)
2016-04-16 04:17:49,744:DEBUG:Write /200MB.zip (len:4096 offset:209707008)
2016-04-16 04:17:49,745:DEBUG:Write /200MB.zip (len:4096 offset:209711104)
2016-04-16 04:17:49,745:DEBUG:Flush /200MB.zip 1
2016-04-16 04:17:49,746:INFO:_put_file 200MB.zip (len:209715200)
2016-04-16 04:17:49,746:INFO:get_file_versions 200MB.zip
2016-04-16 04:17:50,108:INFO:_delete_file 200MB.zip (0)
2016-04-16 04:17:50,109:INFO:_delete_file File deleted (200MB.zip) 
2016-04-16 04:18:41,221:INFO:_put_file File uploaded (200MB.zip)
2016-04-16 04:18:41,222:DEBUG:Release /200MB.zip 1
2016-04-16 04:18:41,222:DEBUG:Flushing file in case it was dirty
2016-04-16 04:18:41,223:DEBUG:Flush 200MB.zip 1
2016-04-16 04:18:41,223:DEBUG:File not dirty, skipping upload
2016-04-16 04:18:41,223:DEBUG:Memory consumption overflow, purging file
2016-04-16 04:18:41,223:DEBUG:File 200MB.zip was chosen for purging, this will free 200 MB

**Comment by falense** [comment] 2016-04-16 10:11
@SpyderZ  Have you removed part of the output? There is no python error in your post, only a traceback of function calls.

As mentioned previously, both of you will have issues as Backblaze only recently released large file support and this is not yet supported by B2Fuse. With a 700MB file chances are high that the upload fail, there is currently no handling of failed uploads built into B2Fuse. 

Also keep in mind that there is an overhead when working with files, even though you have 1GB of memory you may not be able to use 1GB files. It is possible that a copy is made of the file when uploading in order to prepare the request to B2 API. Could you try with a file size 45% of your memory and 33%?

**Comment by J-Wick4** [comment] 2016-04-16 10:30
So I did a test and expanded the droplet to 2GB x 2 CPU and tried with a 1GB file and it failed also. This technology looks promising once big file support is properly working. 

I have a low quantity of files, but their all 1GB and have about 20 per batch. 

I wish instead of RAM that we could use tmpfs as an alternative. Is this possible? I'd sacrifice a bit of speed using SSD in place of RAM. 

Else, if RAM is the only way to go, if it had intelligence to measure free RAM and only use 50% of it, dumping and refreshing once full. FTP doesn't have to load a file into memory does it?

**Comment by falense** [comment] 2016-04-16 11:46
Yes, technically storing the file to be uploaded on disk would be possible. 

No, FTP does not load a file into memory but FTP is usually disk backed. This means that the file can be read from the disk as it is being uploaded. This was not an option for B2 previously, as the file had to be provided in a single go (typically from memory). The new large file API supports multi part uploads, which could be used to alleviate this issue.

**Comment by J-Wick4** [comment] 2016-04-16 20:47
That sounds promising, getting large files out of memory because it's a real limiter right now. If you need someone to help test that functionality, let me know. I'd like to be tossing 20GB/day of server backups at B2's pricing.

**Comment by J-Wick4** [comment] 2016-04-16 20:52
Funny, just got this email from BackBlaze, looks like some new just in time features came out to fix these problems. https://www.backblaze.com/blog/b2-big-data-big-files/

**Comment by mattrummler** [comment] 2016-10-14 23:46
Relating to getting large files out of memory, I am utilizing the memory only option (granted my server has 32GB), however the ability for b2fuse to determine how much memory is available and pull only as much as it reasonably can would be extremely valuable for the in-memory solution as well.
(NOTE: I haven't run into any problems yet, though I don't have very many files and nothing larger than MB so far. I expect larger files and large quantities of them. 
If the in-memory only solution already handles this then great).

**Comment by falense** [comment] 2016-11-04 20:32
If you have a bucket with really really many files, I would be interested in hearing about how the new version 1.3 works out. I'll close this in about a weeks time if I don't hear anything. 

We are still fundamentally limited by the meta data needed for each file, but with disk support (instead of memory backed storage) the use of memory should be greatly reduced. 

Best

**Closed as completed** 2016-11-09 20:42 UTC
Labels: bug, help wanted
